# Site settings
title: Womply Developer Blog
# email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Our mission is to use technology and data to grow, protect, and simplify small
  business. Everyday we serve tens of thousands of merchants, across 400+ business
  verticals, in every corner of America.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://womply.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
